config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :posts
  end

  resources :users do
    resources :comments
  end

  root to: "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  #has_many :comments, dependent: :destroy
  validates :title, :content, :user_id, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit :username, :email, :password, :password_confirmation
    end
  end

  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @comment = @user.comments.new
  end

  def create
    @user = User.find(params[:user_id])
    @comment = @user.comments.new(comment_params)
    if @comment.save
      flash[:success] = 'New comment was successfully created'
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        format.js
      end
    else
      flash[:error] = 'New comment was unable to be saved'
      render user_path(@user)
    end
  end

  private
  def comment_params
    params.require(:post).permit(:content, :username)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    if @post.save
      flash[:success] = 'New post was successfully created'
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        format.js
      end
    else
      flash[:error] = 'New post was unable to be saved'
      render user_path(@user)
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then "alert alert-info"
    when 'success' then 'alert alert-success'
    when 'error' then "alert alert-error"
    when 'alert' then "alert alert-warning"
    end
  end
end

app/views/application/index.html.erb
<h1>Application#index</h1>

app/views/comments/_form.html.erb
<%= form_for [@user, @comment], remote :true do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.submit class: 'btn btn-info' %>
<% end %>

app/views/comments/_show.html.erb
<% if @user.comments.any? %>
  <% @user.comments.each do |comment| %>
    <h4><%= comment.username %></h4>
    <p><%= comment.content %></p>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$('form').remove();
$('#new_user_comment_link').show();
$('#comment_show').html('<%= j render "show" %>');

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/new.js.erb
$('#new_user_comment_link').hide().after('<%= j render("form") %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentsBlog3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class ='container'>
        <div class="navbar-brand">
          <%= link_to "Students Blog", root_path %>
        </div>
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            Logged in as <%= current_user.email %> |
            <%= link_to "View Account", user_path(current_user.id) %> |
            <%= link_to "Edit Account", edit_user_registration_path %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> |
            <%= link_to "Sign Up", new_user_registration_path, :method => "get" %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for [@user, @post], remote: true do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :content, id: 'post_content' %><br>
  <%= f.text_area :content %><br>
  <%= f.submit class: 'btn btn-info', id: 'create_post' %>
<% end %>

app/views/posts/_show.html.erb
<% if @user.posts.any? %>
  <% @user.posts.each do |post| %>
    <h3><%= post.title %></h3>
    <p><%= post.content %></p>
  <% end %>
<% end %>

app/views/posts/create.js.erb
$('form').remove();
$('#new_user_post_link').show();
$('#post_show').html('<%= j render "show" %>');

app/views/posts/new.js.erb
$('#new_user_post_link').hide().after('<%= j render("form") %>');

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-6">
    <div id="post_show">
      <%= render "posts/show" %>
    </div>
    <%= link_to 'Add Post', new_user_post_path(@user), id: 'new_user_post_link', remote: true, method: 'get', class: 'btn btn-success' %>
  </div>


</div>